# fly.toml app configuration file generated for de-regenderer on 2024-01-09T09:25:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "de-regenderer"
primary_region = "yyz"

[build]

[mounts]
  source="permanent"
  destination="/permanent"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  DATABASE_PATH = '/permanent/databases'
  WORKING_DIR = '/permanent/temp'

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024